apiVersion: apps/v1
kind: Deployment
metadata:
  name: hacker-adsoftsito
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hacker-adsoftsito
  template:
    metadata:
      labels:
        app: hacker-adsoftsito
    spec:
      containers:
      - image: okteto.dev/hacker-adsoftsito:latest
        name: adsoftsito
        envFrom:
        - configMapRef:
            name: adsoftsito-config
        livenessProbe:
          httpGet:
            path: /ht/
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: hacker-adsoftsito
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "hacker-adsoftsito"
    port: 8080
  selector:
    app: hacker-adsoftsito
