apiVersion: v1
kind: Service
metadata:
  name: adsoft-postgres
  labels:
    app: adsoft-postgres
spec:
  ports:
  - port: 5433
    name: db
  type: ClusterIP  
  selector:
    app: adsoft-postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: adsoft-postgres
spec:
  selector:
    matchLabels:
      app: adsoft-postgres
  replicas: 1
  serviceName: adsoft-postgres
  template:
    metadata:
      labels:
        app: adsoft-postgres
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: adsoft-postgres
        image: postgres:14
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5433
          name: db
        env:
        - name: PGDATA
          value: /data/pgdata
        envFrom:
        - configMapRef:
            name: postgres-config
        volumeMounts:
        - name: db
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: db
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
